accumulate_grad_batches: 1
audio_num_mel_bins: 80
audio_sample_rate: 48000
#base_config:
#- configs/tts/vctk/resample.yaml
binarization_args:
  resample_ratio: 0.5
  shuffle: false
  with_align: false
  with_f0: true
  with_f0cwt: true
  with_resample: true
  with_spk_embed: false
  with_txt: true
  with_wav: true
#binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer
#binary_data_dir: data/binary/vctk_wav
check_val_every_n_epoch: 10
clip_grad_norm: 1
debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
dict_dir: ''
disc_start_steps: 40000
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  lr: 5.0e-05
  weight_decay: 0.0
discriminator_params:
  bias: true
  conv_channels: 64
  in_channels: 1
  kernel_size: 3
  layers: 10
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.2
  out_channels: 1
  use_weight_norm: true
discriminator_scheduler_params:
  gamma: 0.5
  step_size: 200000
dropout: 0.1
ds_workers: 4
enc_ffn_kernel_size: 9
enc_layers: 4
endless_ds: true
ffn_act: gelu
ffn_padding: SAME
fft_size: 1024
fmax: 7600
fmin: 80
format: hdf5
gen_dir_name: ''
generator_grad_norm: 10
generator_optimizer_params:
  eps: 1.0e-06
  lr: 0.0001
  weight_decay: 0.0
generator_params:
  aux_channels: 80
  aux_context_window: 2
  dropout: 0.0
  gate_channels: 128
  in_channels: 1
  kernel_size: 3
  layers: 30
  out_channels: 1
  residual_channels: 64
  skip_channels: 64
  stacks: 3
  upsample_net: ConvInUpsampleNetwork
  upsample_params:
    upsample_scales:
    - 4
    - 4
    - 4
    - 4
  use_pitch_embed: false
  use_weight_norm: true
generator_scheduler_params:
  gamma: 0.5
  step_size: 200000
griffin_lim_iters: 60
hidden_size: 384
hop_size: 256
infer: false
is_freqwg: false
islb2lr: false
lambda_adv: 4.0
load_ckpt: ''
log_interval: 100
loud_norm: false
lr: 1e-4
max_epochs: 1000
max_eval_sentences: 1
max_eval_tokens: 60000
max_frames: 1550
max_input_tokens: 400
max_samples: 12800
max_sentences: 12
max_tokens: 30000
max_updates: 1000000
mel_vmax: 1.5
mel_vmin: -6
min_level_db: -100
model_class: WaveGlowMelHF
n_fft: 32
num_ckpt_keep: 3
num_heads: 2
num_mels: 80
num_sanity_val_steps: 5
num_spk: 400
num_test_samples: 5
num_valid_plots: 5
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pre_align_args:
  allow_no_txt: false
  denoise: false
  forced_align: mfa
  txt_processor: en
  use_sox: false
  use_tone: true
pre_align_cls: ''
prenet_dropout: 0.5
prenet_hidden_size: 256
print_nan_grads: false
processed_data_dir: data/processed/vctk
profile_infer: false
raw_data_dir: data/raw/VCTK-Corpus
ref_level_db: 20
reset_phone_dict: true
sampling_rate: 48000
save_best: true
save_ckpt: true
save_codes:
- configs
- modules
- tasks
- utils
- usr
save_f0: false
save_gt: true
seed: 1234
sort_by_len: true
stft_loss_params:
  fft_sizes:
  - 1024
  - 2048
  - 512
  hop_sizes:
  - 120
  - 240
  - 50
  win_lengths:
  - 600
  - 1200
  - 240
  window: hann_window
stop_token_weight: 5.0
task_cls: tasks.super_resolution.waveglow_hf.WaveGlowHFTask
test_ids:
- 12
- 23
- 34
- 45
- 56
- 67
- 70
- 74
- 87
- 99
test_input_dir: ''
test_num: 100
test_set_name: test
train_set_name: train
use_mel_loss: false
val_check_interval: 200
valid_set_name: valid
vocoder: pwg
vocoder_ckpt: ''
warmup_updates: 8000
waveglow_config:
  WN_config:
    kernel_size: 3
    n_channels: 256
    n_layers: 8
  embed_dim: 400
  embed_num: 256
  mu: 256
  n_early_every: 4
  n_early_size: 2
  n_flows: 12
  n_group: 8
weight_decay: 0
win_length: null
win_size: 1024
window: hann
#work_dir: checkpoints/glowmultin
